from product.viewsets.product_viewset import ProductViewSet
from product.viewsets.category_viewset import CategoryViewSet
from product.viewsets.details_viewset import DetailsViewSet
from product.viewsets.images_viewset import ImagesViewSet
