# Generated by Django 5.1 on 2024-09-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = []
