# Generated by Django 5.1 on 2024-09-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20240909_1837"),
    ]

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="banner",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="poster",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.details",
            ),
            preserve_default=False,
        ),
    ]
