# Generated by Django 5.1 on 2024-09-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_details_product_banner_product_poster_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="overview",
        ),
        migrations.RemoveField(
            model_name="details",
            name="active",
        ),
        migrations.RemoveField(
            model_name="details",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="banner",
        ),
        migrations.AddField(
            model_name="details",
            name="banner",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
