# Generated by Django 5.1.1 on 2024-09-14 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_poster_remove_images_posters_images_posters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="posters",
        ),
        migrations.AddField(
            model_name="poster",
            name="images",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product.images",
            ),
            preserve_default=False,
        ),
    ]
