# Generated by Django 5.1.1 on 2024-09-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_poster_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posters",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_path", models.CharField(max_length=300)),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posters",
                        to="product.images",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Poster",
        ),
    ]
